version: '3.8'

volumes:
  database_cs:
  static_cs:
  media_cs:

services:

  cleanpro_database:
    image: postgres:15-alpine
    volumes:
      - database_cs:/var/lib/postgresql/data/
    env_file:
      - backend/.env

  cleanpro_redis:
    image: redis:7.2.1-alpine

  cleanpro_backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: backend/.env
    volumes:
      - static_cs:/app/static
      - media_cs:/app/media
    depends_on:
      - cleanpro_database
      - cleanpro_redis

  cleanpro_frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - static_cs:/app/dist
    depends_on:
      - cleanpro_backend

  cleanpro_gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - static_cs:/var/html/static/
      - media_cs:/var/html/media/
    depends_on:
      - cleanpro_backend
      - cleanpro_frontend
