FROM nginx:1.19.3-alpine
LABEL description="Cleanpro" \
      version="0.5" \
      maintainer="TheSuncatcher222" \
      deployer="https://github.com/TheSuncatcher222"
COPY nginx.conf /etc/nginx/templates/default.conf.template
